feat: implemented button icons with stories
internet-identity-labs/NFID-SDK pull request #28
Opened 2022-04-12 18:12 UTC by Mert75

Added new icons and also refactored existing ones accordingly

2022-04-12 19:44 UTC, plitzenberger requested changes
small change please. Also shouldn't icons be separate instead nested in buttons?

2022-04-12 19:44 UTC, plitzenberger commented on packages/nfid-sdk-react/src/atoms/button/icons/index.stories.tsx
> +    window.alert('Clicked!');
Use [storybook actions instead](https://storybook.js.org/docs/react/essentials/actions)

2022-04-12 19:44 UTC, plitzenberger commented on packages/nfid-sdk-react/src/atoms/button/index.stories.tsx
> +    window.alert('Clicked!');
same as above

2022-04-12 20:43 UTC, Mert75 commented
> small change please. Also shouldn't icons be separate instead nested in buttons?

technically yes. with the current approach, not really. 

A List also has a subfolder with icons which are meant for lists only, as well as Input. So these are all icons meant for Button specifically

2022-04-13 06:52 UTC, plitzenberger approved these changes
lgtm

2022-04-13 06:53 UTC, merged