fix([sc-1495]): input error icon alignment
internet-identity-labs/NFID-SDK pull request #90
Opened 2022-05-10 04:45 UTC by chorniy8pavlo

2022-05-11 07:11 UTC, plitzenberger commented on packages/nfid-sdk-react/src/atoms/input/index.tsx
> +            <span className='absolute right-3 top-[50%] translate-y-[-50%]'>
```suggestion
            <span className='absolute right-3 top-1/2 translate-y-1/2'>
```

2022-05-11 07:12 UTC, plitzenberger commented on packages/nfid-sdk-react/src/atoms/input/index.tsx
> +  extends React.InputHTMLAttributes<HTMLInputElement> {
```suggestion
  extends React.InputHTMLAttributes<HTMLDivElement> {
```

2022-05-11 07:12 UTC, plitzenberger requested changes
Please prevent arbitrary styles when possible

2022-05-11 10:23 UTC, chorniy8pavlo commented on packages/nfid-sdk-react/src/atoms/input/index.tsx
> +  extends React.InputHTMLAttributes<HTMLInputElement> {
why HTMLDiv? It's Input component

2022-05-19 13:34 UTC, QuopHi-Geek approved these changes

2022-05-26 00:15 UTC, merged